services:
  frontend:
    build:
      context: .
      args:
        - VITE_GTAG_ID=${VITE_GTAG_ID}
        - VITE_ERP_BASE_URL=${VITE_ERP_BASE_URL}
    container_name: revosolve-website
    ports:
      - "8083:80"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - revosolve-net
networks:
  revosolve-net:
    driver: bridge
