services:
  frontend:
    build: .
    container_name: revosolve-website-prod
    ports:
      - "8084:80"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - revosolve-net
networks:
  revosolve-net:
    driver: bridge
